### ISSUE TITLE
Naming of template and items

### ISSUE THREAD

**Issue by rxt360** [lesovsky/zabbix-extensions#15]
I installed your template and am glad it was easy to install. 

What I don't understand is the naming you use. Everywhere I see "Zabbix", I would use "Postgres" in the XML template. In fact, I did so, and that makes things a lot clearer. I didn't change the xml tags, just "Zabbix" with capital Z. See the txt attachment - XML is not accepted for uploads.

[Postgres-Server-Template.txt](https://github.com/lesovsky/zabbix-extensions/files/50956/Postgres-Server-Template.txt)

**Comment by stephankn** [comment]
Recent Template does not include "Zabbix". Keys seem reasonable named to me. Can this issue be closed?
