### ISSUE TITLE
monitoring skytools

### ISSUE THREAD

**Issue by ghost** [lesovsky/zabbix-extensions#20]
Алексей, приветствую.

Кроме как у тебя, готовый шаблон для skytools со скриптами обнаружения, больше нигде не нашел.
У тебя он не обновлялся более 2 лет, и, по большому счету, в нем есть все необходимо.
Как ты считаешь, что туда можно еще добавить? Не менялся ли он у тебя локально никак?

Спасибо за ответ.

**Comment by lesovsky** [comment]
Привет, я давно не заглядывал в skytools поэтому сходу не скажу что там можно нового добавить. Локально никак не менялся.

**Comment by stephankn** [comment]
Please send a pull request in case you have updates to skytools you like to see merged. Please test against current long-term version of zabbix.
