### ISSUE TITLE
Received value [ERROR: column "waiting" does not existLINE 1: select count(*) from pg_stat_activity where waiting ^] is not suitable for value type [Numeric (unsigned)] and data type [Decimal]

### ISSUE THREAD

**Issue by Netbulae** [lesovsky/zabbix-extensions#29]
Error in zabbix:
`Received value [ERROR: column "waiting" does not existLINE 1: select count(*) from pg_stat_activity where waiting ^] is not suitable for value type [Numeric (unsigned)] and data type [Decimal]`

As kan be read on the [pg_activity](https://github.com/julmon/pg_activity/issues/56) github, there has been a change in the pg_stat_activity.wait. For Postgresql 9.6 postgresql.conf needs to be changed to 

`UserParameter=pgsql.connections.waiting[*],psql -qAtX $1 -c "select count(*) from pg_stat_activity where wait_event"`

**Comment by stephankn** [comment]
This was fixed in #35
