### ISSUE TITLE
postgresql-extended-template.xml unexpected tag "preprocessing".

### ISSUE THREAD

**Issue by azhestov** [lesovsky/zabbix-extensions#48]
Hi.
Ubuntu 16.04, zabbix 3.4.14 pgsql (upgraded from 3.2.9)
import postgresql-extended-template.xml is failed with error
Invalid tag "/zabbix_export/templates/template(1)/items/item(1)": unexpected tag "preprocessing".
What could cause this problem and how to solve it correctly?

**Comment by stephankn** [comment]
can you please double-check that you are really running zabbix 3.4.14? Did you restart the server after updating the packages? 

The template was exported from exactly this version. Also importing the template on a test system running this version works fine.

**Comment by azhestov** [comment]
yes. i recheck it another time. Here copy from page bottom "Zabbix 3.4.14. © 2001–2018, Zabbix SIA"
Of course i restart server because it can't be updated without stop\start. 
# dpkg -l|grep zabbix-server
ii  zabbix-server-pgsql                   1:3.4.14-1+xenial
# zabbix_server -V
zabbix_server (Zabbix) 3.4.14

**Comment by stephankn** [comment]
The update notes mention a dependency on PCRE. Please double-check these notes.

https://www.zabbix.com/documentation/3.4/manual/installation/upgrade_notes_340

Can you also double-check the xml file you are importing is not broken? Maybe you can calculate CRC32 or SHA-1/2 hash, so I can compare it with what is in the repository.

You imported using a browser, right? What browser/host system did you use? How did you get the xml file there?

**Comment by azhestov** [comment]
I was upgrade with deb packages from official zabbix repo, so i think is compliled right and check dependency when install. Additionally i was check file by size, and try download it twice 
1 by git clone 
2 by wget https://raw.githubusercontent.com/lesovsky/zabbix-extensions/master/files/postgresql/postgresql-extended-template.xml

crc here
$ cksum postgresql-extended-template.xml
2219850413 257726 postgresql-extended-template.xml

I was try import it by chromium 68.0.3440.75, firefox 62.0.3 (64-bit), and opera 56.0.3051.36
with this error any time

**Comment by stephankn** [comment]
Happy to hear that it is resolved using the latest version of the repository.

I will close this issue. Feel free to open a new issue if you encounter other problems or have suggestions.
