### ISSUE TITLE
Does it support zabbix 4 and pg 10 ?

### ISSUE THREAD

**Issue by TheMMcOfficial** [lesovsky/zabbix-extensions#54]
I want to install your product but I don't know if it will work with my environement... If not do you know a product who support it ?

**Comment by stephankn** [comment]
My test environment is not yet fully upgraded to version 4, but with that being a LTS I fully commit myself to supporting it.

Postgresql 10 is also supported.

Would be great if you give it a try and give some feedback in case you ran into problems or feel some part of the documentation should be improved (which certainly could benefit in some areas)

**Comment by myhellone** [comment]
Work on zabbix 4.0.2 and Postgres10

**Comment by stephankn** [comment]
thanks. I'll clarify the README.
