### ISSUE TITLE
remove Russian comment

### ISSUE THREAD

**Issue by TEH30P** [lesovsky/zabbix-extensions#68]
Простите за ехидное замечание, но так однако факт: https://github.com/lesovsky/zabbix-extensions/blob/master/files/linux/scripts/mem-usage.sh

**Comment by stephankn** [comment]
I would like to help, but I don't understand the issue. Could you please explain in English?

**Comment by TEH30P** [comment]
Sorry, my bad! Well there is a russian comments in script located [here](https://github.com/lesovsky/zabbix-extensions/blob/master/files/linux/scripts/mem-usage.sh), so i think it shoud be in english.

**Comment by stephankn** [comment]
I agree with that. Can you propose a better comment describing what the file does? Using Google Translate is not a real option for me.

Otherwise a complete rewrite of the comment could be done as well. The file itself has some (non-critical) issues reported with ShellCheck. These could be addressed at the same time.

**Comment by TEH30P** [comment]
So we have two guys: one of them have low english and second one have zero russian, and they try to translate rus->eng. Sounds funny, :)
OK. I have try to make that comment simplest as much, and i got this: 
> Эта проверка выполняется чтоб определить момент когда использование памяти подходит к критической границе: когда кэши невозможно занять, память заполнена и система вот-вот начнет агрессивно свопиться.
,,, and google made this for me:
> This check is performed to determine the moment when the memory usage approaches the critical boundary: when the caches cannot be occupied, the memory is full and the system is about to begin to swap aggressively.
Look good... for me. What is your assessment?

**Comment by stephankn** [comment]
But why all these calculations? Why not simply MemAvailable from meminfo? If available memory without swap gets low the system starts swapping. Sounds for me like the same result, just cheaper calculations.

**Comment by lesovsky** [comment]
fixed 4906384

**Comment by lesovsky** [comment]
@stephankn all these calculation and this file was created when there was no MemAvailable in /proc/meminfo. So it's a legacy code and it can be replaced with better thing if you wish.

**Comment by stephankn** [comment]
thanks. I will consider this. Thinking to re-write some tools to take advantage of json features more to reduce load on the agent side. With 4.0 LTS released I am considering to bump the minimum supported version. Supporting the latest LTS version sounds enough, given the limited time I (or you) can spent on it.

**Comment by Evg33** [comment]
@stephankn hint: http://translate.google.com
