### ISSUE TITLE
pgsql.ping

### ISSUE THREAD

**Issue by jangaraj** [lesovsky/zabbix-extensions#7]
I found one issue with pgsql.ping command

    echo -e "\\\timing \n select 1" | psql -qAtX $1 |grep Time |cut -d' ' -f2

Ubuntu, Zabbix 2.4.3, command is executed in sh, not bash by zabbix, so it has a problem with "-e" parameter; updated command:

    echo "\\\timing \n select 1" | psql -qAtX $1 |grep Time |cut -d' ' -f2

Please test/update. Thx.

**Comment by lesovsky** [comment]
Yes, the sh shell in Ubuntu is dash. Its built-in echo doesn't have an -e option. Replaced it with /bin/echo instead.
