### ISSUE TITLE
formulaid missing in pgbouncer-extended-template.xml

### ISSUE THREAD

**Issue by scott-steadman** [lesovsky/zabbix-extensions#98]
I managed to get it working in Zabbix 5.0

[pgbouncer-extended-template.zip](https://github.com/lesovsky/zabbix-extensions/files/8855187/pgbouncer-extended-template.zip)

**Comment by stephankn** [comment]
Thanks @scott-steadman for your submission. I will take your zip and create a pull request from it.
The failing import on formulaid is a known issue on zabbix: https://support.zabbix.com/browse/ZBX-19968
I guess it is ok to no longer support Zabbix 4.0 LTS, as it is now officially in limited support only. No one will set up new monitoring on such old versions.

**Comment by scott-steadman** [comment]
It may import into 4.0 LTS.  I didn't test it.

**Comment by stephankn** [comment]
It won't import. Your template has version 5.0 in it. Zabbix can import templates of older versions, but not the other way around.
